### ISSUE TITLE
Missing top row (still)

### ISSUE THREAD

**Issue by robertpdx** [JavascriptBattle/javascript-battle-website#334]
I'm not sure if the edits to BoardView.js need to be rolled out by the engine, but the issue still exists.  Are changes to BoardView.js incorporated into dist/javascript-battle-website.min.js? BoardView.js is commented out on the main page (when viewing source).

**Comment by Yahkob** [comment]
@robertpdx sorry know this has took quite a while to fix all of us that started this project have jobs and have been pretty busy the commented out code doesn't have anything to do with this issue was just an alternate way of doing things. I'm going to fix it this weekend until then feel free to pull request as always.

**Comment by Yahkob** [comment]
@robertpdx sorry for the wait, all of us have been pretty busy for the last few months. Just fixed this with latest commit, seems it was a weird compiler issue.
